# See https://github.com/nuxt/module-builder/blob/main/.github/workflows/ci.yml

name: Release version

on:
  push:
    branches:
      - main
      - develop
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  ci:
    environment: ${{ github.ref_name }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

          # writes "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" to /tmp/.npmrc
          registry-url: "https://npm.pkg.github.com"

      - run: |
          git config user.name "$USERNAME"
          git config user.email "$USERNAME@$ADDRESS_SUFFIX"
        env:
          USERNAME: ${{ github.actor }}
          ADDRESS_SUFFIX: users.noreply.github.com

      - run: npm publish
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOGEN_TOKENS_GITHUB: ${{ secrets.GITHUB_TOKEN }}

      - run: npm publish --tag beta
        if: ${{ github.ref == 'refs/heads/develop' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOGEN_TOKENS_GITHUB: ${{ secrets.GITHUB_TOKEN }}
